version: "3.8"
services:
  weather-api:
    image: moazamali4567/weather-app-api:v1
    ports:
      - "8000:8000"
    volumes:
      - ./weather.db:/app/weather.db
    env_file:
      - .env
  weather-client:
    image: moazamali4567/weather-app-client:v1
    command: python main.py
    depends_on:
      - weather-api
    env_file:
      - .env
